In [1]:
import numpy as np
import pandas as pd

In [2]:
!pip3 install scikit-learn

You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -m pip install --upgrade pip' command.


In [3]:
from sklearn import datasets

In [4]:
# Load Boston Housing dataset
diabetes_data = datasets.load_diabetes(as_frame=True)

In [5]:
type(diabetes_data)

sklearn.utils.Bunch

In [6]:
data = diabetes_data["data"]
feature_names = diabetes_data["feature_names"]

In [7]:
data.isnull().sum()

age    0
sex    0
bmi    0
bp     0
s1     0
s2     0
s3     0
s4     0
s5     0
s6     0
dtype: int64

    Algorithm:
    1. Estimate a linear regression where:
        1. Y is variable to imput
        2. X is the rest of dataset
    2. We have b hat. Now we need b star
    3. Draw randomly from posterior predictive distribution and produce b star
    4. Draw randomly (using function) from Multivariate Normal Distribution where:
        1. Mean is b hat
        2. Variance is sigma squared (variance of residuals) multiplied by variance-covariance matrix of b hat
    5. Calculatye predicted values for observed and missing Y:
        1. Use b hat for observed Y
        2. Use b star for missing Y
    6. For each case where Y is missing, find 3 closest predicted values where Y is observed (from Y we predicted for observed cases)
    7. Draw randomly one of these 3 close cases and Impute missing Yi with the observed value of the close case
    Suggestions: https://statisticsglobe.com/predictive-mean-matching-imputation-method/

In [74]:
from sklearn.linear_model import LinearRegression

In [75]:
# y = 1 * x_0 + 2 * x_1 + 3
X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
# y = 1 * x_0 + 2 * x_1 + 3
y = np.dot(X, np.array([1, 2])) + 3
print(y)

[ 6  8  9 11]


In [76]:
reg = LinearRegression().fit(X, y)
reg.score(X, y)

1.0

In [77]:
reg.coef_

array([1., 2.])

In [78]:
reg.intercept_

3.000000000000001

In [79]:
b_hat = [reg.intercept_] + list(reg.coef_)

In [80]:
b_hat

[3.000000000000001, 1.0000000000000002, 1.9999999999999993]

In [81]:
y_true = y
y_pred = reg.predict(X)
print(y_pred, y_true)

[ 6.  8.  9. 11.] [ 6  8  9 11]


In [88]:
mean = b_hat
variance_residuals = np.var((y_true - y_pred))
var_covar = np.cov([b_hat, b_hat], rowvar=True)

In [87]:
print(var_covar)

[[1. 1.]
 [1. 1.]]


In [59]:
variance_residuals = np.var((y_true - y_pred))
var_covar = np.cov([b_hat, b_hat], rowvar=True)
total_variance = variance_residuals * var_covar

In [60]:
total_variance

array([[0., 0.],
       [0., 0.]])

In [32]:
b_hat

[1, 2, 3]

In [37]:
print([b_hat,b_hat])

[[[1, 2, 3]], [[1, 2, 3]]]


In [38]:
(b_hat, b_hat)

([[1, 2, 3]], [[1, 2, 3]])

In [41]:
print(zip(b_hat, b_hat))

In [42]:
np.array((b_hat, b_hat))

array([[[1, 2, 3]],

       [[1, 2, 3]]])

In [44]:
b_hat[0]

[1, 2, 3]

In [69]:
print([b_hat, b_hat])

[[3.000000000000001, 1.0000000000000002, 1.9999999999999993], [3.000000000000001, 1.0000000000000002, 1.9999999999999993]]


In [71]:
print([b_hat, b_hat])

[[3.000000000000001, 1.0000000000000002, 1.9999999999999993], [3.000000000000001, 1.0000000000000002, 1.9999999999999993]]


In [73]:
np.var(([b_hat, b_hat]) )

0.6666666666666671

In [99]:
np.cov(np.array([b_hat]).T)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: Degrees of freedom <= 0 for slice
  """Entry point for launching an IPython kernel.
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/lib/function_base.py:2542: RuntimeWarning: divide by zero encountered in true_divide
  c *= np.true_divide(1, fact)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/lib/function_base.py:2542: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)


array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan]])